#ifndef GLOBAL_H_INCLUDED
#define GLOBAL_H_INCLUDED

#define ENLARGE_PARAM 4
#define WINDOW_WIDTH 800*ENLARGE_PARAM
#define WINDOW_HEIGHT 600*ENLARGE_PARAM


#define FONT_SIZE 12
#define GRID_WIDTH 24
#define GRID_HEIGHT 24

// direction
typedef enum _DIR {UP, DOWN, LEFT, RIGHT, NON} DIR;
#define DIR_KINDS 4

#endif // GLOBAL_H_INCLUDED
